name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Release Version
        default: v1.x
        required: true

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-18.04
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      version: ${{ steps.tag.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Fetch Version
        id: tag
        run: |
          if [[ "${{ github.event.inputs.version }}" != "" ]]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
          fi
      - name: Update Tag
        uses: richardsimko/update-tag@v1
        with:
          tag_name: ${{ steps.tag.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.version }}
          name: "Lite XL Threads ${{ steps.tag.outputs.version }}"
          draft: true
          body_path: changelog.md
          generate_release_notes: true

  build_linux:
    name: Linux
    needs: release
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        arch: [x86_64, i686, aarch64]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Python Setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt -y install ninja-build wayland-protocols libsdl2-dev libfreetype6
          if [[ "${{ matrix.arch }}" != "x86_64" ]]; then
            sudo apt -y install gcc-${{ matrix.arch }}-linux-gnu
          fi
          pip3 install meson
      - name: Build
        run: |
          ls /usr/bin
          if [[ "${{ matrix.arch }}" != "x86_64" ]]; then
            meson setup --cross-file crossfiles/linux_${{ matrix.arch }}.conf \
              --wrap-mode forcefallback -Dprefer_static=true \
              build
          else
            meson setup --wrap-mode forcefallback -Dprefer_static=true build
          fi
          meson compile -C build
          mv build/thread.so thread.${{ matrix.arch }}-linux.so
      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.release.outputs.version }}
          draft: true
          files: thread.${{ matrix.arch }}-linux.so

  build_windows:
    name: Windows
    needs: release
    runs-on: windows-2019
    strategy:
      matrix:
        msystem: [MINGW32, MINGW64]
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: true
          install: >-
            base-devel
            git
            zip
      - name: Set Environment Variables
        run: |
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          if [[ "${MSYSTEM}" == "MINGW64" ]]; then
            echo "PLATFORM=x86_64-windows" >> "$GITHUB_ENV"
          else
            echo "PLATFORM=x86-windows" >> "$GITHUB_ENV"
          fi
      - name: Install Dependencies
        run: |
          pacman --noconfirm -S \
            ${MINGW_PACKAGE_PREFIX}-{gcc,meson,ninja,ntldd,pkg-config,mesa,freetype,pcre2,SDL2} unzip
      - name: Build
        run: |
          meson setup --wrap-mode forcefallback -Dprefer_static=true build
          meson compile -C build
          ntldd -R "build/thread.dll"
          mv build/thread.dll thread.${PLATFORM}.dll
      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.release.outputs.version }}
          draft: true
          files: thread.${{ env.PLATFORM }}.dll

  build_macos:
    name: macOS
    needs: release
    runs-on: macos-11
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    env:
      CC: clang
      CXX: clang++
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Python Setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          brew install bash ninja sdl2
          pip3 install meson
      - name: Build
        run: |
          if [[ "${{ matrix.arch }}" == "aarch64" ]]; then
            meson setup --cross-file crossfiles/macos_arm64.conf \
              --wrap-mode forcefallback -Dprefer_static=true \
              build
          else
            meson setup --wrap-mode forcefallback -Dprefer_static=true build
          fi
          meson compile -C build
          mv build/thread.so thread.${{ matrix.arch }}-darwin.so
      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.release.outputs.version }}
          draft: true
          files: thread.${{ matrix.arch }}-darwin.so
